### ISSUE TITLE
Why do you restrict to 4 verbs ?

### ISSUE THREAD

**Issue by neolao** [laurisvan/request-promise-lite#10]
There are other verbs in HTTP like PATCH

**Comment by laurisvan** [comment]
Yep, I should add PATCH, OPTIONS, HEAD and TRACE - I've been incrementally adding things when one needs them.

I will add these, please stay tuned.

**Comment by laurisvan** [comment]
Resolved in #11 .

Now request-promise-lite Request class supports everything Node.js claims to support (see https://nodejs.org/api/http.html#http_http_methods). I also created aliases in index.js for TRACE, OPTIONS, HEAD and PATCH.

I'm closing this issue, as I believe it got fixed. Feel free to reopen, if I didn't get something covered.
