### ISSUE TITLE
Please provide type declaration

### ISSUE THREAD

**Issue by balassy** [laurisvan/request-promise-lite#14]
Hello Lauri,

I like how lightweight is this lib, and thanks for creating and maintaining it. I use it from TypeScript, but without type definition it is really painful. Could you please create a `.d.ts` file and publish it to the `@types/request-promise-lite` package?

This article can be helpful: https://blogs.msdn.microsoft.com/typescript/2016/12/14/writing-dts-files-for-types/

Thanks,
György

**Comment by laurisvan** [comment]
Hi & thanks for using the lib!

I haven't been using TypeScript before, but learning that is definitely in my plans. I got a good excuse for that now, so I'll have a look this weekend. Sounds reasonable!

**Comment by balassy** [comment]
Awesome, thanks a lot!

**Comment by laurisvan** [comment]
@balassy I did a quick study on TypeScript definitions and exported the public interface of this library. I didn't submit a PR to DefinitelyTyped yet, because I'm not probably the best person to evaluate if it is ready. It passes the tsc compiler, but I'm not 100% use if it works in use as expected.

Could you please check https://github.com/laurisvan/DefinitelyTyped, perhaps try it and let me know if something is lacking? The module is called 'request-promise-lite' as expected.

**Comment by laurisvan** [comment]
BTW I'd very much like to maintain these definitions in this repo, but I'd like to keep the release small. If you have good hints on how to publish TypeScript definitions without maintaining a fork of DefinitelyTyped, I'd be definitely interested.

And very interested to getting a PR into this repo directly - would love to get community contributions!

**Comment by balassy** [comment]
I agree, that seems to be a logical decision. You can add an `index.d.ts` file to the root of your library, and that will do the job without a separate `@types` package. 
Read more: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

Hope this helps,
György

**Comment by balassy** [comment]
I've downloaded the `index.d.ts` file you added to your DefinitelyTyped fork, and added to my project, and it seems working perfectly, though currently I'm using only the `get` function of our library.

**Comment by laurisvan** [comment]
I finally added the TypeScript definitions at #23 . Sorry for taking so long - it took this long until I got my first TypeScript project to really use it in practice (I was a bit hesitant to merge something I did not use before).

The fix should land at RPL 0.13

**Comment by balassy** [comment]
Awesome, thank you very much, Lauri!
