### ISSUE TITLE
Add Verbose option back

### ISSUE THREAD

**Issue by qswinson** [laurisvan/request-promise-lite#19]
In addition to allowing a logging strategy to be injected into the library, pull request #17 removed the ability to conditionally log a specific request. In my opinion this is a breaking change because the previous default was not to log unless specified and now everything is logged. The only way to prevent this excess logging is to overwrite the library's logging function to an empty function. There is not enough context passed into the logging function to be able to determine if the request should be conditionally logged which is something that the previous verbose option allowed. The strategy used for logging should be independent of the need to log a specific request.

I've decided to not upgrade to the new version because of this issue.

**Comment by laurisvan** [comment]
Hi, let me find a workaround for this one. It's a shame if it causes trouble for you. Maybe a default logger that would work in the same way as the previous release would do the job?

@medikoo What do you think would be the best solution from your viewpoint?

**Comment by laurisvan** [comment]
I think I might have found a workaround, please see #20 . @medikoo @qswinson would this work for you guys?

Especially pay attention that now the verbose mode should be back and work as before. However, the logger implementation API changed slightly - I think it is much better to reflect through defaults than modifying a required module.

**Comment by medikoo** [comment]
I think whether logs should be output or not is better if decided with environment settings, and not within application logic (in request options). It's also what other similar utilities do (e.g. [request](https://github.com/request/request#debugging))

Usual case is that we may want to log in production or when we debug certain issues, but e.g. have very same logs silent in tests or normal dev work.

Anyway if proposed change, doesn't affect ability to control logs purely via environment settings, from my point of view then it's not harmful.

Still @laurisvan be sure to check that it doesn't affect `maas-transport-booking`, I think proposed change, if supposed to be taken in to `maas-transport-booking`, will require certain updates over there (especially that many requests where left with `verbose: true`, that will have to be removed)

**Comment by medikoo** [comment]
What definitely could be an improvement is to not log by default. I think it was mistake to keep it _on_ by default after removing `verbose` option.

**Comment by laurisvan** [comment]
Ok, I can change the implementation so that verbose mode affects to logging, and the default logger is console logger.

E.g. when verbose: true, it would log whatever needs to the specified logger (that defaults to ConsoleLogger, but that can be switched to whatever).

**Comment by samuelcarreira** [comment]
Hi, first of all, congrats for your great work on this library. I will give a try to it on my project.

I also would like to know how to disable the verbose option (I tried the `verbose: false` and the `const req = request.Request.defaults.verbose = true ` without any success. The only option that I found was to manually edit the logger.js file

Can you teach me **how to disable the console log/verbose feature**? It's kind of annoying have the console polluted with all the request details each time I make a request.

Thank you and keep the good work :clap:

**Comment by qswinson** [comment]
I think PR #20 looks good. I like that it keeps the original straight forward ability to log requests if desired, but gives the ability to control the logger implementation if needed. 

@samuelcarreira - The current release does not support the verbose flag. Pull request #20 adds it back, but that has not yet been merged and released. I would recommend referencing version 0.6.2 until the next release. The only change to 0.7.0 was to the logging feature.

**Comment by medikoo** [comment]
> Can you teach me __how to disable the console log/verbose feature__? 

@samuelcarreira you can silence all logs by adding following somewhere at start of your application:

```javascript
require('request-promise-lite/lib/logger').log = function () {};
```

**Comment by laurisvan** [comment]
Ok if this works for you guys I'll go and merge the PR.

@medikoo I'll create a PR for MaaS repos so that the new release won't cause regression. I'll bump the minor version for this release. As we are still under 1.0 (e.g. no stable API yet), I think that's the semantically most correct way to communicate the changes.

**Comment by laurisvan** [comment]
Oh, the new tool I used for publishing (np, https://www.npmjs.com/package/np) bumped a few more versions than I expected.

Well regardless, the 0.12 minor version should solve this problem.

**Comment by medikoo** [comment]
> @medikoo I'll create a PR for MaaS repos so that the new release won't cause regression. 

Ok
