### ISSUE TITLE
Unexpected response type handling

### ISSUE THREAD

**Issue by Feijk** [laurisvan/request-promise-lite#2]
When requesting JSON, but receiving for instance HTML, or some other form of invalid data, the library will fail during response parsing. Any thoughts on how to handle these situations?

**Comment by laurisvan** [comment]
As a quick workaround, you could write the request content type specifically, and when leaving 'json' out, it would not parse it in any way, and return a plain buffer. You could then parse it as you please.

**Comment by laurisvan** [comment]
The 0.6.1 version is able to catch the potential type conversion issues. But in case the request & response types mismatch, I suggest reading the raw response. In case of JSON in some cases, HTML in some cases the solution might be as simple as:

const options
request.get(url, options)
  .then(buffer => JSON.parse(buffer.toString()))
  .catch(error => // Handle parse error)

I'll close this for now.
