### ISSUE TITLE
Timeout option

### ISSUE THREAD

**Issue by joshillian** [laurisvan/request-promise-lite#21]
A timeout option that emulates request's timeout functionality would be a nice-to-have feature.

**Comment by laurisvan** [comment]
If there's a PR, I will definitely add this one. Any volunteers? I can also work on this one, but it'll take a while.

**Comment by joshillian** [comment]
I'm in the same boat - it might take me a while to get back to this as I am no longer actively using the tool set.  But once I do, I'll definitely try and invest some time to it.  Would be worthwhile to have in this great, great project.

**Comment by laurisvan** [comment]
Would it be API-wise sufficient to have a timeout parameter in options (in the same way as 'request' module, https://www.npmjs.com/package/request#requestoptions-callback)? 

Technically that is only about socket timeout - if there is something else that stalls, it would not be shown. However, I have hard time thinking anything else that might stall.

**Comment by laurisvan** [comment]
@joshillian Would you think this PR would suffice your needs? https://github.com/laurisvan/request-promise-lite/pull/24

**Comment by joshillian** [comment]
That looks like it'll fit the bill! Thanks @laurisvan!

**Comment by laurisvan** [comment]
Hrm it looks like Travis is unable to set the socket timeout explicitly - everything with tests works just fine locally. I'll check it out later tonight and if I manage to get it working, I'll merge this to master.

**Comment by konker** [comment]
I didn't realise that a PR had already been started and made my own.
https://github.com/laurisvan/request-promise-lite/pull/27

**Comment by laurisvan** [comment]
Since the solution by @konker' actually works, I merged that in and published as 0.14.0.

I'm closing this bug now - thanks for your contributions & sorry for the delay!
