### ISSUE TITLE
Release new version and push to npm

### ISSUE THREAD

**Issue by swftvsn** [laurisvan/request-promise-lite#29]
Hi! 

Could you push new version to npm, please? I need to copy the types by hand each time I do changes that result npm overwriting the hand picked files :/

Thanks!

**Comment by laurisvan** [comment]
Hi @swftvsn!

I'm replying very quickly now (many things ongoing in parallel) - sorry if I missed something.

Just to double-check, 0.14.0 is the latest in NPM and at the same time the one in master branch. The new types should be there already since 0.13.1. Am I missing something?

**Comment by swftvsn** [comment]
0.14.0 was released a couple of months ago, but I'm referring to #28 that got committed 25 days ago, but has not been released afaik?

**Comment by laurisvan** [comment]
Ah ok, got it. 0.15 it is - just fresh in the npm repo!
