### ISSUE TITLE
Leak of tcp socket when using keepAlive connections and response is a redirect

### ISSUE THREAD

**Issue by Nicolas-Duboc-IBM** [laurisvan/request-promise-lite#32]
When using an http agent which keeps tcp connections alive  (e.g.  `http.globalAgent.keepAlive = true;`),
if an http response to a Request is a "302 redirect",
then another tcp connection from the agent pool is used to honor the redirect, but the first one is not released and returned to the pool of "free" connections, so will never be reused.

Pull request https://github.com/laurisvan/request-promise-lite/pull/31 proposes a fix for this issue.

**Comment by laurisvan** [comment]
Merged your PR and released it as a part of the latest update. Thanks for your contribution!
