### ISSUE TITLE
Connection errors are thrown as unhandled errors

### ISSUE THREAD

**Issue by amv** [laurisvan/request-promise-lite#5]
I have a `test.js` file containing:

```
require('request-promise-lite')
  .get('http://127.0.0.1:4822/no_server_in_port')
  .catch( function( error ) {
    console.log("I handled this error:", error );
  } );
```

And running that gets me:

```
$ node test.js
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:4822
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
```

I guess this is not by design? At least my gut says that all errors like this should just reject the promise instead of throwing an uncaught error.. You agree?

**Comment by laurisvan** [comment]
True, we do not yet have a class/mechanism for handling connection errors & various runtime errors.

I was thinking maybe we should introduce a few subclasses of RequestError, e.g. HTTPError (HTTP semantics) and ConnectionError (the other various errors like invalid host etc.)? I'd say the different runtime errors could stay as-is.

How about semantic errors, with e.g. user asking a for JSON and despite content negotiation the value is returned as HTML? Would that be a connection error or sth else?

**Comment by laurisvan** [comment]
@amv Would this suffice for your needs - care to review?

https://github.com/laurisvan/request-promise-lite/pull/6

**Comment by amv** [comment]
I post-merge-reviewed this ;) and although it did contain a bit of other stuff as well, I think at least the error stuff was good. abort and aborted were good additions in addition to catching error.
